name: Run Tests

on:
  push:
    branches: [ main ]

jobs:
  run-pester-tests:
    uses: ./.github/workflows/run-tests.yml
  update-artifacts:
    if: github.ref != 'refs/heads/main'
    uses: ./.github/workflows/update-artifacts.yml
    needs: run-pester-tests
    permissions:
      contents: write
