name: Run Pester Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install required modules
        run: |
          Install-Module -Name FormatMarkdownTable -Force -Scope CurrentUser
        shell: pwsh

      - name: Perform a Pester test from the Tests.ps1 file
        shell: pwsh
        run: |
          Invoke-Pester -Passthru
