name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-pester-tests:
    name: Run Pester Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install required modules
        shell: pwsh
        run: |
          Install-Module -Name FormatMarkdownTable -Force -Scope CurrentUser

      - name: Invoke Pester to run all tests
        shell: pwsh
        run: |
          Invoke-Pester -Passthru
