name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-pester-tests:
    name: Run Pester Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install required modules
        shell: pwsh
        run: |
          Install-Module -Name FormatMarkdownTable -Force -Scope CurrentUser

      - name: Perform a Pester test from the Tests.ps1 file
        shell: pwsh
        run: |
          Invoke-Pester -Passthru
